server:
  applicationConnectors:
    - type: http
      port: 8080

logging:
  level: WARN
  loggers:
    se.citerus: DEBUG

  appenders:
    - type: console

eventStore : se.citerus.cqrs.bookstore.infrastructure.SimpleFileBasedEventStore
#eventStore : se.citerus.cqrs.bookstore.infrastructure.InMemoryDomainEventStore